### ISSUE TITLE
Build fail on macOS Apple Silicone

### ISSUE THREAD

**Issue by naymapl** [aperture-software/colditz-escape#10]
I have xcode, x-quartz, glew. I got error after `make release`:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -Cfreeglut libfreeglut.a
make[1]: `libfreeglut.a' is up to date.
gcc -o colditz conf.o dictionary.o game.o graphics.o getopt.o iniparser.o low-level.o main.o md5.o soundplayer.o osx/audio_backend.o -L/opt/homebrew/opt/zlib/lib -L./freeglut -L/opt/X11/lib -lfreeglut -lX11 -lXi -lXmu -lXext -lGL -lGLU -lGLEW -framework CoreFoundation -framework IOKit -framework CoreAudio -framework AudioUnit
ld: library not found for -lGLEW
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [colditz] Error 1
```

Any idea what is wrong ?

**Comment by aperture-software** [comment]
Per the [Mac build process](https://github.com/aperture-software/colditz-escape/blob/master/.travis.yml) you must have the following dependencies installed:
- libgl1-mesa-dev
- libglu1-mesa-dev
- libxmu-dev
- libxi-dev
- libglew-dev
- libexpat-dev
- libasound-dev

I'm pretty sure you are missing at least libglew-dev.

Now whether these libraries are available for Apple Silicon, that's a different story...
