### ISSUE TITLE
Error executing file

### ISSUE THREAD

**Issue by inakogf** [aperture-software/colditz-escape#11]
Colditz Escape 1.2.133
by Aperture Software - 2009-2017

Can't open shader file 'SHADERS/HQ2X.GLSL' for reading
Couldn't find file 'COLDITZ_ROOM_MAPS'

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by aperture-software** [comment]
Make sure you extract all the files. You also don't indicate what version you are using, which makes it very difficult to test.
