### ISSUE TITLE
👋  Maps 🗺️ 

### ISSUE THREAD

**Issue by matthutchinson** [aperture-software/colditz-escape#13]
Not an issue, but just though I'd point you to [these game maps I drew as a kid](https://www.reddit.com/r/thisweekinretro/comments/14966un/found_old_escape_maps_escape_from_colditz_amiga/) 

Awesome to discover this repo and your old site, [still up via archive.org](https://web.archive.org/web/20160409151825/https://sites.google.com/site/colditzescape/) !!

~Do you still have the "goodies/ReverseEngineeringAnalysis.7z" file you referenced on the site?~

UPDATE: [Found it](https://github.com/aperture-software/colditz-escape/blob/master/docs/files/Reverse%20Engineering%20Analysis.7z)

**Comment by aperture-software** [comment]
That's great. Thank you.
