### ISSUE TITLE
check_footprint issue

### ISSUE THREAD

**Issue by picryott** [aperture-software/colditz-escape#3]
In room #320, the character can cross the lower limit.
![ce check_footprint failure](https://cloud.githubusercontent.com/assets/28193457/26033833/5c53ef5e-38b3-11e7-976c-788bf3eea5f4.jpg)
To get to room #320, start with the english prisoner and use the stair to go up 1 level.

**Comment by aperture-software** [comment]
Thanks for the report. I can replicate the issue, and have confirmed that this is not a bug from the original. I'll see what I can do to fix it.
