### ISSUE TITLE
corrupted display on first multiview for PSP

### ISSUE THREAD

**Issue by picryott** [aperture-software/colditz-escape#6]
ON PPSSPP, the display is corrupted the first time you ask for multiview.
If you ask again, the display is fine.

![menu_00000](https://cloud.githubusercontent.com/assets/28193457/26284783/48253a20-3e43-11e7-9012-e5ae22c6e456.jpg)

**Comment by aperture-software** [comment]
Yes, I had noticed that too. Will see what I can do.
