### ISSUE TITLE
Can you help with what is probably something simple?

### ISSUE THREAD

**Issue by davidk64fnq** [aperture-software/colditz-escape#9]
![Screen Shot 2020-04-21 at 8 37 54 PM](https://user-images.githubusercontent.com/63939880/79858125-429bb580-8412-11ea-99ff-a33982633678.png)

Please see screenshot hopefully attached.

Let me know if more info needed.

Hope you can help.

Cheers David

**Comment by aperture-software** [comment]
You need to `cd` to the directory before you launch the app:

```
cd /Users/Mills/Documents/Colditz\ Escape
./colditz
```

**Comment by davidk64fnq** [comment]
Thanks! I'm a twit.
    On Tuesday, 21 April 2020, 9:11:46 PM AEST, Aperture Software <notifications@github.com> wrote:  
 
 


You need to cd to the directory before you launch the app:
cd /Users/Mills/Documents/Colditz\ Escape
./colditz
